### ISSUE TITLE
Button not disabled?

### ISSUE THREAD

**Issue by vguna** [DocX/ng-promise-button#4]
The documentation states, that the button will be disabled during async operation. This doesn't seem to happen ;). Looking through the code for disabled, I couldn't find any disabled behavior. I'm missing something?

**Comment by DocX** [comment]
Hi vguna.

Thanks for question. Can you post example of code how do you use it?

Thanks

**Comment by vguna** [comment]
Ok, I think that was my wrong understanding of "disabled".
I thought it sets the disabled class or sets ng-disabled="true".
But looking at the demo it seems to work as advertised.
Sorry for the misunderstanding :).

Am 24.02.2016 um 23:59 schrieb Lukáš Doležal:

> Hi vguna.
> 
> Thanks for question. Can you post example of code how do you use it?
> 
> Thanks
>
